name: Main
on: push

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - run: terraform fmt -check -diff
  Validate:
    runs-on: ubuntu-latest
    steps:
      - run: terraform validate
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: terraform-linters/setup-tflint@v4
      - run: tflint -f compact
      - run: ls
