name: Main
on: push

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: terraform fmt -check -diff
  Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: terraform validate
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4
      - run: tflint -f compact
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
      - run: terraform init
      - run: terraform plan -out=.tfplan
      - run: terraform apply -auto-approve .tfplan
      - run: terraform plan -detailed-exitcode -refresh=false
      - run: terraform destroy -auto-approve -refresh=false
        if: always()
